server:
  port: 8081

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/brainspace?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 50000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false

  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    locations: filesystem:db/migration

mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.springframework.boot.autoconfigure: warn
    com.brainspace.wx: debug

